[project]
name = "agents-v1"
version = "0.1.0"
description = "Create Agents v1"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.3",
    "azure-ai-agents>=1.1.0",
    "azure-ai-projects>=1.0.0",
    "azure-identity>=1.25.0",
]
